### ISSUE TITLE
Examples throw error, don't seem to import in Three.js

### ISSUE THREAD

**Issue by jondavis847** [ModiaSim/Modia3D.jl#119]
I recently tried to run the examples in Modia3D. I only installed the package and tried to run each of the examples in the tutorial such as:

include("$(Modia3D.path)/test/Tutorial/Pendulum1.jl")

This throws the following error:
julia> include("$(Modia3D.path)/test/Tutorial/Pendulum1.jl")

Instantiating model Pendulum
  in module: Main.Pendulum1
  in file: C:\Users\jonda\.julia\packages\Modia3D\il61O\test\Tutorial\Pendulum1.jl:11
ERROR: 
solution = simulate!(Pendulum, ...) failed with solution.retcode = :Success at time = 3.0.

Stacktrace:
 [1] error(::String, ::String, ::String)
   @ Base .\error.jl:44
 [2] macro expansion
   @ C:\Users\jonda\.julia\packages\Modia\TXKQS\src\SimulateAndPlot.jl:246 [inlined]
 [3] macro expansion
   @ C:\Users\jonda\.julia\packages\TimerOutputs\LHjFw\src\TimerOutput.jl:237 [inlined]
 [4] simulate!(m::Modia.SimulationModel{Float64, Float64}, algorithm::Missing; merge::Nothing, kwargs::Base.Pairs{Symbol, Float64, Tuple{Symbol}, 
NamedTuple{(:stopTime,), Tuple{Float64}}})
   @ Modia C:\Users\jonda\.julia\packages\Modia\TXKQS\src\SimulateAndPlot.jl:235
 [5] top-level scope
   @ C:\Users\jonda\.julia\packages\Modia3D\il61O\test\Tutorial\Pendulum1.jl:12

Same error for each of the examples in the tutorial. It does produce the .json files and there appears to be data inside of them. However, if I try to import them into Three.js, nothing happens. The rendered scene just stays empty.

**Comment by AndreaNeumayr** [comment]
Did you install the Modia package as well? Please see [installation guide](https://github.com/ModiaSim/Modia3D.jl/wiki/Full-Installation-Guide-for-Julia,-Modia3D,-Modia). Which Julia version do you use?

Visualization with Three.js:
In example `Tutorial/Pendulum1.jl` there is nothing to visualize (no 3D shape is defined, etc.). So you don't get a visualization at all.
In example `Tutorial/Pendulum2.jl` there is a Solid [shape](https://modiasim.github.io/Modia3D.jl/stable/Components/Shapes.html) (Beam) with visualization properties defined. There you'd get a visualization with Three.js. 

Since the example fails with an error you don't get a reasonable visualization.

**Comment by GerhardHippmann** [comment]
At the moment animation export is broken because the [object names in three.js have been changed](https://github.com/mrdoob/three.js/pull/24349) (e.g. "SphereBufferGeometry" -> "SphereGeometry"). A fix is implemented but not yet published.

**Comment by jondavis847** [comment]
Thanks for the help! Indeed I needed Modia to drop the error when simulating, I had poorly assumed Modia3D would bring Modia with it. I searched for "Buffer" in my .json file for the animation. I found only one instance of a CylinderBufferGeometry. Changing that to CylinderGeometry and importing the .json file to Three.js worked great.

"geometries": [
{
"name": "obj2.geometry",
"uuid": "0bfc5553-48e7-5e27-84a7-3518139b6ca3",
"type": "CylinderBufferGeometry",
"radiusBottom": 0.05,
"radiusTop": 0.05,
"height": 0.21,
"radialSegments": 32,
"heightSegments": 1
},
